---
- hosts: all
  become: true
  gather_facts: no

  # fix when no Python is installed yet
  pre_tasks:
    - name: Install Python
      raw: sudo apt-get -y install python

    - name: Gather facts
      setup:

  vars_prompt:
    - name: user_password
      prompt: "Password to set for user"
      default: "vagrant"

  roles:
    - create-user
