---
- hosts: all
  become: true
  gather_facts: no

  # fix when no Python is installed yet
  pre_tasks:
    - name: Install Python
      raw: sudo apt-get -y install python

    - name: Gather facts
      setup:

  roles:
    - bootstrap
    - firewall
    - php
    - nginx
    - default-website
    - mariadb
    - composer
    - nodejs
    - clean-up
